import { jsPDF } from 'jspdf'
import type { DocumentVerification, CitationVerification, ComplianceReport } from '../schema.js'
import { SCOPE_SHORT } from '../verify/scope.js'
import { logoBase64 } from './logo.js'

const GREEN = '#3B6D11'
const DARK = '#111110'
const GRAY = '#888780'

export function generateVerificationPdf(dv: DocumentVerification, compliance?: ComplianceReport): Buffer {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const pageW = 210
  const margin = 20
  const contentW = pageW - margin * 2
  let y = margin

  const bold = (text: string, size: number, color?: string) => {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(size)
    doc.setTextColor(color ?? DARK)
    doc.text(text, margin, y)
  }

  const normal = (text: string, size: number, color?: string) => {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(size)
    doc.setTextColor(color ?? DARK)
    doc.text(text, margin, y)
  }

  const line = (h: number = 5) => { y += h }

  const checkPage = () => {
    if (y > 270) {
      doc.addPage()
      y = margin
    }
  }

  // Header
  doc.addImage(logoBase64, 'PNG', margin, y, 40.8, 16.8)
  y += 22
  normal('Citation Verification Report', 8, GRAY)
  line(8)
  doc.setDrawColor(GRAY)
  doc.line(margin, y, pageW - margin, y)
  line(8)

  // Document info
  bold('Document', 11, DARK)
  line(6)
  normal(`Name: ${dv.document_name}`, 9)
  line(5)
  normal(`Hash: ${dv.document_hash.slice(0, 16)}...`, 9, GRAY)
  line(5)
  normal(`Verified: ${dv.checked_at}`, 9, GRAY)
  line(5)
  normal(`Duration: ${dv.duration_ms}ms`, 9, GRAY)
  line(8)

  // Summary
  bold('Summary', 11, DARK)
  line(6)
  normal(`Total citations: ${dv.total_citations}`, 9)
  line(5)
  normal(`Verified:        ${dv.verified_count}`, 9, GREEN)
  line(5)
  normal(`Hallucinated:    ${dv.hallucinated_count}`, 9, '#f85149')
  line(5)
  normal(`Misattributed:   ${dv.misattributed_count}`, 9, '#d29922')
  line(5)
  normal(`Unverifiable:    ${dv.unverifiable_count}`, 9, GRAY)
  line(5)
  normal(`Pending:         ${dv.pending_count}`, 9, GRAY)
  line(5)
  normal(`Confidence:      ${(dv.overall_score * 100).toFixed(0)}%`, 9)
  line(5)
  normal(`Coverage: ${dv.coverage_summary.covered} covered, ${dv.coverage_summary.partial} partial, ${dv.coverage_summary.uncovered} uncovered`, 9, GRAY)
  line(8)

  // Compliance
  if (compliance) {
    bold('Compliance', 11, compliance.passed ? GREEN : '#f85149')
    line(6)
    normal(`Standard: ${compliance.standard}`, 9)
    line(5)
    normal(`Jurisdiction: ${compliance.jurisdiction}`, 9, GRAY)
    line(5)
    normal(`Result: ${compliance.passed ? 'PASS' : 'FAIL'}`, 9, compliance.passed ? GREEN : '#f85149')
    line(5)
    normal(`Score: ${(compliance.score * 100).toFixed(0)}%`, 9)
    line(5)
    normal(`Expires: ${compliance.expires_at}`, 9, GRAY)
    line(5)
    normal(`Summary: ${compliance.summary}`, 9)
    line(8)

    // Findings
    bold('Findings', 11, DARK)
    line(6)
    for (const f of compliance.findings) {
      checkPage()
      normal(`${f.met ? '✔' : '✘'} ${f.rule_id}: ${f.requirement}`, 8)
      line(4)
      normal(`  ${f.detail}`, 7, GRAY)
      line(6)
    }
    line(4)
  }

  // Citation detail
  checkPage()
  bold('Citations', 11, DARK)
  line(6)

  for (const cv of dv.citations) {
    checkPage()
    const statusColor = cv.status === 'verified' ? GREEN : cv.status === 'hallucinated' ? '#f85149' : GRAY
    const label = `${cv.status.toUpperCase()} (${(cv.confidence * 100).toFixed(0)}%)`
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(statusColor)
    doc.text(`[${label}]`, margin, y)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(DARK)
    const textX = margin + 30
    const lines = doc.splitTextToSize(cv.citation.raw_text, contentW - 30)
    doc.text(lines, textX, y)
    line(lines.length * 4 + 3)

    if (cv.sources_checked.length > 0) {
      const sourceCount = cv.sources_checked.filter(s => s.found || s.error).length
      if (sourceCount > 0) {
        normal(`  Sources: ${sourceCount} checked`, 7, GRAY)
        line(4)
      }
    }
    line(2)
  }

  // Scope notice
  line(4)
  doc.setDrawColor(GRAY)
  doc.line(margin, y, pageW - margin, y)
  line(4)
  doc.setFont('helvetica', 'italic')
  doc.setFontSize(7)
  doc.setTextColor(GRAY)
  const scopeLines = doc.splitTextToSize(SCOPE_SHORT, contentW)
  doc.text(scopeLines, margin, y)
  y += scopeLines.length * 3 + 4

  // Footer
  line(4)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  doc.setTextColor(GRAY)
  doc.text(`Generated by LegalVerify v0.2.0 | github.com/tensflare/verify`, margin, y)

  return Buffer.from(doc.output('arraybuffer'))
}
